[package]
name = "viatls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20", features = [ "full" ] }
tokio-rustls = "0.23.4"
webpki-roots = "0.22"
rustls-pemfile = "1.0.1"
anyhow = "1.0.66"
structopt = "0.3.23"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
socks5-proto = { version = "0.3.2" }
socks5-server = { version = "0.8.2" }
bytes = "1.2.1"
futures-util = { version = "0.3.25", default-features = false, features = ["sink", "std"] }
tungstenite = { git = "https://github.com/ssrlive/tungstenite-rs.git", branch = "mychange", features = [ "rustls-tls-webpki-roots" ] }
tokio-tungstenite = { git = "https://github.com/ssrlive/tokio-tungstenite.git", branch = "mychange", features = [ "rustls-tls-webpki-roots" ]  }
rustls = "0.20.1"
url = "2.3.1"
base64 = "0.13.0"
log = "0.4.17"
env_logger = "0.9.0"
http = "0.2.5"
httparse = "1.8.0"
